from trainer.base_trainer import Trainer
from trainer.simclr_trainer import SimCLRTrainer
from trainer.multitask_trainer import MultitaskSimCLRTrainer
from trainer.multitask_supervised_trainer import MultitaskTrainer

from trainer.multiaugment_trainer import MultiaugmentSimCLRTrainer, TAGTrainer
from trainer.bilevel_trainer import BilevelTrainer